### ISSUE TITLE
Add more database connections

### ISSUE THREAD

**Issue by Langriklol** [baraja-core/doctrine#26]
- Is your feature request related to a problem?
Yes, as I cannot use more than 1 database in whole project
- Explain your intentions.
Add another connection support in neon package configuration
- It's up to you to make a strong case to convince the project's developers of the merits of this feature.
<strong :convince="true">CASE</strong>

**Comment by janbarasek** [comment]
Connecting multiple databases can be handled by configuration in the NEON file. However, creating an `EntityManager` service uses a fixed connection on the `Connection` object.

Please try to figure out how inject different EntityManagers within the DIC will work.

If I simply use `EntityManagerInterface` or `EntityManager`, the primary database is used. But how to use the other databases? How to handle cases where a third party package requires `EntityManager` but the developer wants to pass another instance to it?

Thank you.

**Comment by janbarasek** [comment]
I have tested connecting to multiple databases and Doctrine does not support such settings. So I can't support it.
