### ISSUE TITLE
Incompatibility with symfony/console 5.0.*

### ISSUE THREAD

**Issue by miloshavlicek** [baraja-core/doctrine#7]
This package depends on symfony/console ^4.2.3, however I use symfony/console 5.0.8

**Comment by janbarasek** [comment]
Yes, I should upgrade this dependency. Thanks.

**Comment by janbarasek** [comment]
Support for `symfony/console` v5.0.*  added and created tag `v2.1.0`: https://github.com/baraja-core/doctrine/releases/tag/v2.1.0

Test: https://github.com/baraja-core/doctrine/pull/8/checks?check_run_id=647474824#step:4:123

![Snímek obrazovky 2020-05-05 v 22 48 52](https://user-images.githubusercontent.com/4738758/81114578-9930e580-8f22-11ea-800a-5196f4f66d2b.png)

Thanks!
